# Generated by Django 4.2.21 on 2025-06-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seri",
            name="tahun_seri",
        ),
        migrations.AddField(
            model_name="laptop",
            name="tahun_seri",
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
