# Generated by Django 4.2.21 on 2025-06-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_seri_tahun_seri_laptop_tahun_seri"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(default="Bio", max_length=200),
            preserve_default=False,
        ),
    ]
