# Generated by Django 4.2.21 on 2025-06-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_laptop_description_profile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
    ]
